name: 'Check FL ticket in PR name'

on:
  push:
    branches:
      - dev

env:
  FBT_TOOLCHAIN_PATH: /runner/_work

jobs:
  merge_report:
    runs-on: [self-hosted,FlipperZeroShell]
    steps:
      - name: 'Wipe workspace'
        run: find ./ -mount -maxdepth 1 -exec rm -rf {} \; 

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Get commit details'
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
          else
            TYPE="other"
          fi
          python3 scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE" || cat "${{ github.event_path }}"

      - name: 'Check ticket and report'
        run: |
          source scripts/toolchain/fbtenv.sh
          python3 -m pip install slack_sdk
          python3 scripts/merge_report_qa.py \
              ${{ secrets.QA_REPORT_SLACK_TOKEN }} \
              ${{ secrets.QA_REPORT_SLACK_CHANNEL }}

