# Configuration for welcome - https://github.com/behaviorbot/welcome
newIssueWelcomeComment: >
  Congrats on opening your first issue on this repository! 🎉<br>
  This is a automated message to help you avoid common pitfalls when asking for help online.<br>
  👉 Be sure to:<br>
  * 🇬🇧 Communicate in English so everybody can understand you<br>
  * 📖 Have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki) and [README](https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/README.md) for information<br>
  * 🔍 Search for similar [issues (open and closed)](https://github.com/SpacehuhnTech/esp8266_deauther/issues?q=is%3Aissue+)<br>
  * ✍️ Provide enough information to understand, recreate and help out with your problem<br>
  * ℹ️ Let us know if you find a solution and please share it with us<br>
  * 📕 Close the issue when your problem has been solved

newPRWelcomeComment: 

firstPRMergeComment: 
