name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-fap:
    runs-on: ubuntu-latest
    container:
      image: an4tur0r/flipperzero-unleashed:latest
      env:
        APP_NAME: xbox_controller
      volumes:
        - ${{ github.workspace }}:/flipperzero-unleashed/applications_user/xbox_controller
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd /flipperzero-unleashed
          ./fbt fap_xbox_controller
          cp build/f7-firmware-D/.extapps/xbox_controller.fap applications_user/xbox_controller/
      - uses: actions/upload-artifact@v3
        with:
          name: xbox_controller
          path: ./xbox_controller.fap