remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Flipper Zero Payloads
description: List of free and open source payloads for Flipper Zero
show_downloads: true
google_analytics: G-7PFFNGGJQL
copyright: "2023"
logo: "img/logo-repository.png"
