name: Build FAP

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: oleksiikutuzov/flipperzero-ufbt-action@v2
      with:
        channel: rc
